Fix #411 Allow to specify kind of code action to execute
joaotavora/eglot pull request #598
Opened 2021-01-23 11:27 UTC by muffinmad

Make `eglot-code-actions` accept `action-kind` argument.  If there are
only one action of that kind, apply it.
This will allow to create actions shortcuts like

    (defun eglot-code-action-organize-imports ()
      (interactive)
      (eglot-code-actions nil nil "source.organizeImports"))

* eglot.el (eglot-code-actions): Accept new argument `action-kind`.  Execute
the only action of that kind.

2021-01-23 11:43 UTC, joaotavora commented
> This will allow to create actions shortcuts like

These shortcuts may be simple enough that they can be in `eglot.el` itself.  But I don't see why they shouldn't _also_ take `beg` and `end`, for completeness.

2021-01-23 11:50 UTC, muffinmad commented
> > This will allow to create actions shortcuts like
> 
> These shortcuts may be simple enough that they can be in `eglot.el` itself. But I don't see why they shouldn't _also_ take `beg` and `end`, for completeness.

Agree. If you think those shortcuts are not worth a separate PR, I can add it here.

2021-01-23 11:54 UTC, joaotavora requested changes
Please try to do the Lisp refactorings I suggest, otherwise go ahead and I'll do this cleanup later.  Conceptually, I think the code is clean.

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +         (end (if beg
Nitpick:  this is perhaps a bit silly and personal preference, but you think you could use more of the line up to 70-80 characters so that we get a more compact definition.  It hurts readability for me (though I suppose it _helps_ readability for you).  So 80 lines is the limit (kind of a soft one), but do use the limit.

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +                 (append
I think you can use the `,@` trick here instead of calling `append`.  It's one less level to read.  Look in the file, I'm sure I use it often.  It looks like:
```
`(:foo :bar ,@(when bazp `(:baz)))
```

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +          (or (cl-remove-if-not
It looks like you want to filter here. Fine.  But instead of the `cl-remove-if-not #'identity` + `mapcar` that returns nils, better just use `cl-loop` with a `when` and a `collect`.

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +                            (jsonrpc-lambda (&key isPreferred kind
no need to break the line here.

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +                              (and isPreferred
You're kind of re-doing the filtering again here.  Fell free to reorder the code, so that the `cl-find-if` fails if the "preferred" action is not there anymore because it was excluded from that loop earlier on.

2021-01-23 11:54 UTC, joaotavora commented on eglot.el
> +                        `("Eglot code actions:" ("dummy" ,@menu-items)))
Like that you inlined this here, but please, longer lines :-D

2021-01-23 11:55 UTC, joaotavora commented
> Agree. If you think those shortcuts are not worth a separate PR, I can add it here.

Agree.  Add them here.  Maybe in a separate commit, but not strictly necessary.

2021-01-23 11:56 UTC, joaotavora commented
If you add the shortcuts, edit the README.md file too to mention them.  Also, edit the NEWS.md file if you can find a terse way to describe this feature.

2021-01-23 15:41 UTC, muffinmad commented
Ok, will do in a few days. Thanks!

2021-01-24 20:34 UTC, mdbergmann commented
Just to confirm that the code as it is seems to work with either code-actions provided by menu and clicking them, and executing a code-action as the example for organize imports at the top post here.

2021-01-26 16:32 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
I'm sorry, I didn't notice this here before.  I think the `regiona-action-p` checks should be in the interactive spec, not in the function's logic. This will also simplify the docstring. Why did you take them out?

2021-01-26 16:34 UTC, joaotavora commented on eglot.el
> +         (default (car (or preferred-action
be careful when using the local variable name "default": it's silly but it leads to stupid indentation sometimes (though not here I think.  That's because emacs mixes it up with a _definition_.  Also, I think this can be on just one line.

2021-01-26 16:34 UTC, joaotavora commented on eglot.el
> +                       (x-popup-menu last-nonmenu-event `("Eglot code actions:" ("dummy" ,@menu-items)))
Aren't these lines too long?

2021-01-26 16:35 UTC, muffinmad commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
> Why did you take them out?

To allow calling `eglot-code-actions` with `nil` as `beg`.

2021-01-26 16:36 UTC, joaotavora commented on eglot.el
> +          (or (cl-loop for action across actions
Are we sure `actions` is _always_ an array?  I'm fine if we are, but I've been bitten by this before in Eglot.

2021-01-26 16:38 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
But why do we want to do that?  `beg` is a "marker or position", there's no reason to lax types like that.  Are you trying to save on user typing?  In which situations exactly?

2021-01-26 16:39 UTC, joaotavora commented on eglot.el
> +                              (and isPreferred
Other than this bit, this is fine to merge (assuming you've tested, of course).

2021-01-26 16:41 UTC, muffinmad commented on eglot.el
> +          (or (cl-loop for action across actions
Well, I've checked `type-of` of the `jsonrpc-request` result and it was `vector`. For me specifying `in` instead `across` gives no results. What is the proper way to loop over actions?

2021-01-26 16:44 UTC, joaotavora commented on eglot.el
> +          (or (cl-loop for action across actions
If something can be a `vector` or a `list` (which includes `nil`) you need to use an iteration variable and a function which can runtime dispatch on the type of sequences.  But if you know it will be a vector, `across` is fine.  The fact that `in` silently fails in a bug in `cl-loop`, in my opinion.

2021-01-26 16:47 UTC, muffinmad commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
I would like to have this code in the interactive spec too, but if we going to create shortcuts like

```elisp
(defun eglot-code-action-inline (&optional beg end)
  (interactive)
  (eglot-code-actions beg end "refactor.inline"))
```

does this mean we should also calculate `beg` and `end` in the interactive specs of each shortcut?

2021-01-26 16:56 UTC, muffinmad commented on eglot.el
> +         (default (car (or preferred-action
Fixed

2021-01-26 16:56 UTC, muffinmad commented on eglot.el
> +                       (x-popup-menu last-nonmenu-event `("Eglot code actions:" ("dummy" ,@menu-items)))
Yes, they are. Fixed.

2021-01-26 16:57 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
Yes, and you can extract a function to simplify that code, code too.  You can call it `eglot--region-bounds`.

2021-01-26 17:02 UTC, muffinmad commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
Got it. Thanks!

2021-01-26 17:03 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
Or in interactive functions that just need `beg` and `end` and nothing else, you can use the built-in `(interactive "r")` which is even shorter.  Do `C-h f` on `interactive` for a look on what it can do.

2021-01-26 17:04 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
In fact, in those shortcuts, `beg` and `end` shouldn't even be optional.

2021-01-26 17:09 UTC, muffinmad commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
With no region selected the `(interactive "r")` will fail with "The mark is not set now, so there is no region". Do you know if it possible to make it to fallout to `(point) nil` if there are no region?

2021-01-26 17:14 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
Oh, I forgot about that.  Well, one way to look at this is to ask ourselves: does it really make sense to invoke code actions without a region? Or should the region be the entire buffer in that situation?

I guess we should do the `eglot--region-bounds` that does the fallback, but probably to the whole buffer.  By the way, I guess we should use `use-region-p`, and not `region-active-p`.

2021-01-26 17:31 UTC, muffinmad commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
> but probably to the whole buffer

Please don't. See https://github.com/joaotavora/eglot/pull/473 :)

2021-01-26 17:38 UTC, joaotavora commented on eglot.el
> +   `(nil nil ,(when current-prefix-arg
I couldn't follow that issue now, but I trust you that defaulting to point is better.

2021-01-26 19:58 UTC, muffinmad commented
> Anyway, please change back to `default`

Can we keep `default-action`? IMO it looks better combined with `preferred-action`.

2021-01-26 20:06 UTC, joaotavora commented
> Can we keep default-action? IMO it looks better combined with preferred-action.

Sure, of course.  Though I personally would do `default` + `preferred`.  But the level of nitpickery is getting extreme here.

2021-01-26 20:40 UTC, muffinmad commented on eglot.el
> +          (or (cl-loop for action across actions
Will using `append` be acceptable here?

```elisp
(cl-loop for action in (append actions nil)
```

2021-01-26 20:43 UTC, joaotavora commented on eglot.el
> +          (or (cl-loop for action across actions
I use that trick sometimes, yes.  It makes a cons cell for every action, which could be wasteful.  But here it isn't too bad because you're not likely to be a big set.  But, I think you're fine with `across` here.

2021-01-27 10:19 UTC, joaotavora commented on eglot.el
> +(defun eglot-code-action-organize-imports (beg &optional end)
These are so identifical, that a `eglot--define-code-action-shortcut` macro is probably in order.  Also, only one line of separation between top-level forms, please.

2021-01-27 12:02 UTC, muffinmad commented on eglot.el
> +(defun eglot-code-action-organize-imports (beg &optional end)
First `cl-loop`, now macro. I learned a lot from this PR, thanks! ;) Please see updated version.

2021-01-28 11:46 UTC, joaotavora commented
I've tweaked this PR.  It's ready for squashing and pushing IMO (after commit msg where I should appear as `Co-authored-by`). But have a look at the tweaks I made and let me know.

BTW your macro was fine, but some people including me, prefer macros to not secretly intern symbols, since it helps when finding definitions.  A function defining macro should theoretically be called `define-foo`, but I let that go here in favour of some terse and readable one-liners.

2021-01-28 12:09 UTC, muffinmad commented
> I've tweaked this PR. It's ready for squashing and pushing IMO (after commit msg where I should appear as `Co-authored-by`). But have a look at the tweaks I made and let me know.

Looks absolutely good to me.

> BTW your macro was fine, but some people including me, prefer macros to not secretly intern symbols, since it helps when finding definitions. A function defining macro should theoretically be called `define-foo`, but I let that go here in favour of some terse and readable one-liners.

Got it. Thanks!

2021-01-28 18:36 UTC, merged