TRAMP support
joaotavora/eglot pull request #637
Opened 2021-03-03 02:24 UTC by bjc

This patch adds TRAMP support to eglot (fixes #84)

I have seen https://github.com/joaotavora/eglot/pull/463 but decided to have another go at it. Some differences include:

  * This patchset includes a test for TRAMP functionality (which doesn't require passwordless ssh to a remote host!)
  * I've copied in Emacs 27.1's `executable-find` to be used on older Emacsen. 27.1 and later will use the native definition.
  * I have not included any special instructions for TRAMP. I do not believe they are necessary. Things work as expected (at least as I expect them to: you define a custom path, it'll be used on the remote. If you don't, it uses your PATH).
  * I have made `server` a mandatory argument to `eglot--uri-to-path`, because I feel it's less error-prone than having a default. Instead, I've passed in the default where necessary.

The one thing I'm not super-keen on in this patch is the use of `stty` when creating the process for the LSP. I don't know any other way to do it, though, and it seems to be how it's done from what I could dig up. It does feel like a bug in Emacs itself, though, that it should be necessary.

2021-03-03 09:40 UTC, joaotavora commented
Interesting!  This looks very good!

> I've copied in Emacs 27.1's executable-find to be used on older Emacsen. 27.1 and later will use the native definition.

If this works, then your executable-find.el shim could maybe be put in a GNU Elpa package. But for now it works, and it's not too much code, so no prob.

> I have made server a mandatory argument to eglot--uri-to-path, because I feel it's less error-prone than having a default. Instead, I've passed in the default where necessary.

I'm not keen on this, but I can be convinced, if you explain why you "fell" it's less error-prone.  In things run in the same stack frame, using a special variable should be just as effective.

> The one thing I'm not super-keen on in this patch is the use of stty 

Yes, but I like that you commented it and isolated it.  I don't fully understand  it, but that's OK.  Can you make a bug report to Emacs and link the resulting discussion thread here?

2021-03-03 09:55 UTC, joaotavora requested changes

2021-03-03 09:55 UTC, joaotavora commented on eglot-tests.el
> +                      (unless (string-equal
Nit: This line doesn't need to be broken anymore

2021-03-03 09:55 UTC, joaotavora commented on eglot-tests.el
> +
Micro-nit. Kill this blank line, pls.

2021-03-03 09:55 UTC, joaotavora commented on eglot-tests.el
> +    ;;
Kill this blank comment line pls.

2021-03-03 09:55 UTC, joaotavora commented on eglot-tests.el
> +    ;;
This one is fine.  I like this style for readability.

2021-03-03 09:55 UTC, joaotavora commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
If this is _exactly_ the same code as you say above, maybe you can extract a function out of it, and call it in two contexts right?

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +  (if (eq 1 (cdr (func-arity 'executable-find)))
These kinds of tests are normally done on `emacs-major-version`, I think.  Also, the indirection should happen at run-time, not compile-time, for better debuggability (unless doing that would present a performance bottleneck, which I don't think it does).

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +                     ((and program (not (eglot--executable-find program t)))
fine, just fine.

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +                            (cmd (list "sh" "-c"
You can't do this unconditionally, right?  Ideally, this is only done when it needs to be done.  Isn't there a way to detect when it must be done?  The `(file-remote-p default-directory)` technique maybe?

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +                         :file-handler t)))))))
Does this work with Emacs 26.3?

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +                            :rootPath (expand-file-name (file-local-name default-directory))
Ah, interesting.  Can you explain why this is needed?

2021-03-03 09:55 UTC, joaotavora commented on eglot.el
> +  "Convert URI to a file path on SERVER.
I've mentioned this is a previous comment.  Can you explain why using `current-server-or-lose` is a bad idea here?

2021-03-03 12:44 UTC, bjc commented on eglot.el
> +                         :file-handler t)))))))
Ugh. No, this was introduced in 27.1. Sorry about that. I'm working on another method with `start-file-process-shell-command`, who's docstring states it goes back to at least 23.1.

2021-03-03 12:46 UTC, joaotavora commented on eglot.el
> +                         :file-handler t)))))))
I don't think you need to do that.  I'm fine with supporting TRAMP only on Emacs 27.1 +.  We just have to make sure to keep supporting basic Eglot functionality in Emacs 26.3.  So please don't add more complexity.  Use this cleaner method.

2021-03-03 12:53 UTC, bjc commented on eglot.el
> +  "Convert URI to a file path on SERVER.
This was just a gut feeling of mine. It came down to a few things:

1. The `uri-to-path` function seems pretty low level to me, and thus can't really know all the contexts in which it's going to be called. Since it requires the server information to perform its duty, it felt like it should also be a required argument.
2. `current-server-or-lose` is basically a global variable, and while useful, limiting its uses to higher-level code makes it more tractable.
3. Lastly, aesthetics. I find the above easier to read and reason about than `(defun eglot--uri-to-path (uri &optional (server (eglot--current-server-or-lose)))…)`

Once I tracked through the places in the code where this function was being called, it turned out to be pretty easy to supply the `server` argument from places where it was passed in via server methods. The remaining places where I had to use `current-server-or-lose` as its value, `current-server-or-lose` was already being used in that section of code (like the `xref` stuff). So that made me feel more confident about the decision to add the new argument.

2021-03-03 12:56 UTC, bjc commented on eglot.el
> +                            :rootPath (expand-file-name (file-local-name default-directory))
`default-directory` will be a TRAMP file name when you're working on TRAMPed files, so it'll look like `/ssh:foo@bar:/some/path/baz.py`, which the language server won't understand. `file-local-name` just removes the TRAMP prefix, making the path look as it would to the remote RLS (eg, `/ssh:foo@bar:/some/path/baz.py` becomes `/some/path/baz.py`)

2021-03-03 12:57 UTC, bjc commented on eglot.el
> +                            (cmd (list "sh" "-c"
While I believe it's safe to do it unconditionally, I'm moving it to a separate code branch that'll only get triggered in `file-remote-p` conditions, since I have to create that branch anyway due to the missing `:file-handler` argument on `make-process` which you point out below.

2021-03-03 12:58 UTC, bjc commented on eglot.el
> +  (if (eq 1 (cdr (func-arity 'executable-find)))
I can definitely move this to a run-time check. I assumed you'd rather it done at compile time, and that seemed to be the style with these compatibility patches.

2021-03-03 12:59 UTC, bjc commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
I'll change the comment. It's not exactly the same, since I must add the TRAMP prefix to the file paths.

2021-03-03 12:59 UTC, joaotavora commented on eglot.el
> +  "Convert URI to a file path on SERVER.
> current-server-or-lose is basically a global variable, and while useful, limiting its uses to higher-level code makes it more tractable.

It's a function it's implemented with a special variable, not exactly a global one. Crucially, the var is not writable per the protocol, unless you violate the protocol. In CL, and in Emacs you have lots of these, just look at CL's `*print-...` stuff.  They influence "lower-level" functions deeply too.

> 3. Lastly, aesthetics. 

You don't have to use an optional argument.  And you needn't give it a default in the `defun`.  And it doesn't work with Elisp defun anyway (you need `cl-defun`).

I'd rather we don't thread the server argument down to every nook and cranny if we can avoid even thinking about it.  Because doing the same thing repeatedly is a maintenance risk, in general.  Bottom line is we want this function to fail loudly if the server isn't available.

2021-03-03 13:05 UTC, joaotavora commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
right, but you can pass that as an argument to the function I'm proposing.  Don't duplicate the test code, is what I'm saying.

2021-03-03 13:07 UTC, joaotavora commented on eglot.el
> +                            (cmd (list "sh" "-c"
> While I believe it's safe to do it unconditionally, 

Didn't you write it doesn't work on non-unix systems?

Also, even on such systems, I don't think we want the shell in the middle unless there some TRAMPiness involved.  So yeah, a different code branch sounds good.

2021-03-03 13:07 UTC, joaotavora commented on eglot.el
> +                            :rootPath (expand-file-name (file-local-name default-directory))
aha. please add this as a comment (as terse as you can make it while still being useful).

2021-03-03 13:46 UTC, joaotavora commented on eglot.el
> +  (if (eq 1 (cdr (func-arity 'executable-find)))
Hmm, I think that's mostly when, say, defining an undefined function.  If you're going to make `eglot--executable-find`, better let it have the same implementation everywhere.

2021-03-03 15:59 UTC, bjc commented on eglot.el
> +                         :file-handler t)))))))
Ok. I've nixxed the `start-file-process-shell-command` branch, and just integrated it directly (with the `file-remote-p` test, as discussed).

It still makes the code a bit messy, since I need a couple of tests to amend the arguments to `make-process` as well as conditionalize the `stty` in the remote case. I can't think of a better way to do it right now, though, short of maybe adding an `eglot--make-process` function, similar to the `eglot--executable-find`, but I'd really like to keep the number of patched functions minimal.

Let me know what you think.

2021-03-03 16:03 UTC, bjc commented on eglot.el
> +                            (cmd (list "sh" "-c"
I've moved this stuff into a separate branch. Regarding the comment, while it's true it won't work on non-unix systems, I don't think TRAMP itself works on non-unix systems, given how it expects to be able to call to a unix shell and modify its prompt.

That said, I like to imagine a future where TRAMP works universally, so I'd still rather not encode unixisms if at all possible.

2021-03-03 16:06 UTC, joaotavora commented on eglot.el
> +                         :file-handler t)))))))
I can't see your code.  Did you push it?  It's fine to rebase and force-push

2021-03-03 16:10 UTC, joaotavora commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
That works too.  As long as you don't write the same sexp twice, you're golden.

2021-03-03 16:11 UTC, joaotavora commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
though perhaps you mean "dynamically binding", or am I missing something?

2021-03-03 16:14 UTC, bjc commented on eglot.el
> +  "Convert URI to a file path on SERVER.
It hadn't occurred to me that I didn't need an optional argument, but of course you are right. I still disagree, as I think the other two points stand, but it's not a big deal to me.

I'll make this change and have `eglot--uri-to-path` be single argument again.

2021-03-03 16:19 UTC, joaotavora commented on eglot.el
> +  "Convert URI to a file path on SERVER.
thank you.  I do find it curious why you think of `eglot--uri-to-path` as "low level". Shouldn't "low-level" function be able to see the dynamic environment?  Or do you want to call it from ouside that environment.  Say, in a debug setting.

By the way, if the server is indeed **optional**, then the correct choice is `eglot--current-server`, **not** `eglot--current-server-or-lose`.  By doing so, you retain the possibility to call `eglot--uri-to-path` from serverless contexts.

2021-03-03 16:46 UTC, bjc commented on eglot-tests.el
> +      (let ((prefix (concat "/test:localhost:" default-directory)))
I confess, sometimes the lisp terminology escapes me. What I mean is that I'm binding the special variable `temporary-file-directory` in a lexical context, via `let`, so that it'll automatically unwind once that block is done. Hopefully it's obvious in the patch what's going on.

2021-03-03 16:47 UTC, bjc commented on eglot.el
> +                         :file-handler t)))))))
Just pushed. I was replying to comments as I worked on it.

2021-03-03 16:51 UTC, joaotavora reviewed
This is looking really good. I'm going to make a commit, which is easier to show you the changes I mean, and then you can test and do further adjustments, OK?

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +    (defun eglot--executable-find (command &optional remote)
I meant doing the test inside the top-level defun.  But don't worry, I can change this.

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +                             (cmd (if (file-remote-p default-directory)
This is too tight for confort, so I'm going to extract a function here.

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +                            ;; Remove Emacs’ remote prefix, if any, so
Gonna put your example, else I won't be able to easily remember what the "remote prefix" really is.

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +    (concat (file-remote-p (project-root (eglot--project
You didn't make it truly optional as you had hinted.  I think that's a good feature.

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +                             (file-chase-links (eglot--executable-find "javac" t))))))))
I'd rather not change this bit yet  Some people seem to rely on this code, which is really brittle (and doesn't even belong in Eglot).

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +  (mapc (lambda (arg) (eglot--apply-workspace-edit arg)) arguments))
Hmmm? Feeling verbose? :-)

2021-03-03 16:51 UTC, joaotavora commented on eglot.el
> +  (mapc (lambda (arg) (eglot--apply-workspace-edit arg)) arguments))
Hmmm? Feeling verbose? :-)

2021-03-03 16:55 UTC, bjc commented on eglot.el
> +  "Convert URI to a file path on SERVER.
Again, this is all just gut. I find it hard to express exactly why I think it's better to have it be explicit. I look at `uri-to-path` as something that does a strict mapping from a URI to a path, a pure function who's inputs soley determine the outputs. Given that view, relying on external state isn't possible.

Now, I confess that I'm pretty fond of pure functions for lots of reasons, and so I try to use them as much as I think is reasonable. An extension of this is to try and limit global context as much as is reasonable.

So to me, it's a trade-off: is it worse to thread the argument through the code, or worse to rely on external context? I felt in this case, the latter, because the function *feels* like a pure function to me, and there wasn't a huge amount of threading necessary, and where it was, it was easy to accomplish.

But this is just a judgement call, and reasonable people can be expected to disagree. I can certainly see why you'd rather rely on using the external state.

2021-03-03 16:56 UTC, bjc commented on eglot.el
> +    (defun eglot--executable-find (command &optional remote)
Ah, ok. I definitely prefer that, too. I get hives when I put imperative code at the top level.

2021-03-03 16:57 UTC, bjc commented on eglot.el
> +    (concat (file-remote-p (project-root (eglot--project
It's not necessary. `file-remote-p` just returns the empty string if it's not remote, and I love removing redundant conditionals.

2021-03-03 16:58 UTC, bjc commented on eglot.el
> +                             (file-chase-links (eglot--executable-find "javac" t))))))))
I struggled here as well, so do what makes sense to you.

2021-03-03 16:59 UTC, bjc commented on eglot.el
> +  (mapc (lambda (arg) (eglot--apply-workspace-edit arg)) arguments))
Oops. This is what happens when I add an argument, then remove it, and miss the obvious trim.

2021-03-03 17:00 UTC, joaotavora commented on eglot.el
> +  "Convert URI to a file path on SERVER.
Heh.  Interesting.  In my view, the function's purity is broken as soon as its main job (converting an URI) is now dependent on an external condition that you pass into the function. You're just dressing up the "impurity" in other ways.  What's the difference between relying on a bunch of arguments threaded down and relying on a bunch of dynamically scoped environment variables?  Just aesthetics.  But I can certainly see your point too.  I've often taken the opposite stance, and sometimes I will thread arguments.

2021-03-03 17:01 UTC, bjc commented
Sure thing. Let me know when to pull your changes.

2021-03-03 17:46 UTC, joaotavora commented
There.   I've simplified this.  Please test.  We probably still ahve to special-case the test to only run in > Emacs 27.1.  Then I'll do the commit message and squash adjustments, crediting you foremost, of course. 

Thanks, this really looks like the lean, simple TRAMP support PR I had been waiting for.

2021-03-03 17:47 UTC, joaotavora commented
Oh no, I commited a bunch of useless files I had lying here.  hehehe time to force push the branch!

2021-03-03 17:49 UTC, joaotavora commented
Done.

2021-03-03 18:07 UTC, bjc commented on eglot.el
> +                         :file-handler t)))))))
Isn't the `:file-handler t` here a problem, or am I missing something?

2021-03-03 18:08 UTC, bjc commented on eglot.el
> +(defun eglot--cmd (contact)
I'm not seeing where this is called. It looks like the `make-process` call, where I'd expect it, is just using a bare `contact`.

2021-03-03 18:08 UTC, joaotavora commented on eglot.el
> +                         :file-handler t)))))))
Doesn't seem to hurt versions of `make-process` which don't support it.

2021-03-03 18:10 UTC, bjc commented on eglot.el
> +    (concat remote-prefix normalized)))
This is harmless, but the `and server` clause shouldn't be needed, since `file-remote-p` will just return the empty string if the file isn't remote.

Is there something I'm missing?

2021-03-03 18:11 UTC, joaotavora commented on eglot.el
> +(defun eglot--cmd (contact)
yup, I forgot it.  Just pushed it.  Doesn't seem to make a different to the test output, whcih is curious. I presume you have ways to test manually with and without that helper.  Please do, and let me know.

2021-03-03 18:12 UTC, joaotavora commented on eglot.el
> +    (concat remote-prefix normalized)))
But there might not be a server in some call scenarios.  Your previous version seemed to be failing a lot of tests.  I haven't dug down, but it seems `server` _does_ need to be optional in practice.  So the `or-lose` idiom doesn't work.

2021-03-03 18:13 UTC, bjc commented on eglot.el
> +                         :file-handler t)))))))
good to know!

2021-03-03 18:14 UTC, joaotavora commented on eglot.el
> +                         :file-handler t)))))))
Doesnt **seem** to ;-)

2021-03-03 18:15 UTC, bjc commented on eglot.el
> +    (concat remote-prefix normalized)))
Gotchya. Thanks for letting me know.

2021-03-03 18:17 UTC, bjc commented
Just pulled the latest from you and everything looks good on my end.

Regarding the test, it's probably best to:
```emacs-lisp
(skip-unless (and (executable-find "pyls") (>= emacs-major-version 27)))
```

2021-03-03 18:18 UTC, joaotavora commented
> Regarding the test, it's probably best to:

yes, exactly

But did you test manually and play around a little bit with tramp?  In Emacs 27.1? Are the simplistic instructions in the README.md correct?

2021-03-03 18:21 UTC, bjc commented
The README seems fine to me. I haven't done any special setup for my TRAMP buffers. I have done some light testing with xref style stuff and variable/method renaming, and it seems to work well.

I do not have Emacs 27 installed, unfortunately. I'm running 28. I'll have to set up a container with 27 to verify it there.

2021-03-03 18:23 UTC, joaotavora commented
Great.

From what I remember from the investigations of #463, I strongly suspect it won't work with Emacs 27.1, so maybe the conditions have to be tweaked But that's fine, really.  Simplicity trumps it.

2021-03-03 18:36 UTC, bjc commented
I've just run some tests against Emacs 27.1, and haven't run into any issues.

2021-03-03 18:50 UTC, joaotavora commented
> I've just run some tests against Emacs 27.1, and haven't run into any issues.

That's even more fantastic.  To think this years-old request was so few lines of code away...

Finally, can you double-check that `eglot--cmd` is _really_ needed?

2021-03-03 19:23 UTC, bjc commented
> > I've just run some tests against Emacs 27.1, and haven't run into any issues.
> 
> That's even more fantastic. To think this years-old request was so few lines of code away...

To be fair, it does rely on features in 27.1 to do it as simply as it does.

> Finally, can you double-check that `eglot--cmd` is _really_ needed?

I have checked this so many times, because I *hate* it. I've just tried again without it, in the vain hope that maybe something miraculous has happened, but no, it's still very definitely required.

I would love to get rid of it, but I think it's going to take some work within Emacs itself to do so. Definitely a project I'm keen on when I get some time for it.

2021-03-04 12:48 UTC, bjc reviewed
This test is still passing for me. Is it failing for you?

2021-03-04 15:02 UTC, joaotavora commented
> This test is still passing for me. Is it failing for you?

Yes, last I checked.  Curious. Are you sure you deleted your elc's and and ran a simple `make check EMACS=whatever/emacs/you/want/src/emacs` ?

2021-03-04 16:13 UTC, bjc commented
I was testing in-Emacs with `M-x ert`, but I've since tried with `make check` with Emacs 27.1, and it still passes.

That said, I'm also using `jedi-language-server` for python, not `pyls`. I was never able to make `pyls` work with eglot (even before my changes) for reasons I never dug into, so maybe that's the issue here?

2021-03-04 16:16 UTC, joaotavora commented
But the tests _are_ running `pyls`, unless you have changed them.  If the tests are passing then `pyls` must somehow be working on your machine.  Here is the output I get around that single failing TRAMP test:
```
   passed   9/43  eglot--glob-test (0.034668 sec)
Tramp: Sending command ‘exec /bin/sh ’
Tramp: Found remote shell prompt on ‘krug’


Tramp: Sending command ‘exec /bin/sh ’
Tramp: Found remote shell prompt on ‘krug’
[eglot] Test body was A FAILURE
[eglot] Killing nil, wiping /loopback:krug:/tmp/eglot--fixtureQsFHHj, restoring nil
Test eglot--tramp-test backtrace:
  signal(wrong-type-argument ("inserted-chars 23"))
  tramp-signal-hook-function(wrong-type-argument ("inserted-chars 23"))
  signal(wrong-type-argument ("inserted-chars 23"))
  tramp-handle-insert-file-contents("/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil)
  apply(tramp-handle-insert-file-contents ("/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil))
  tramp-sh-file-name-handler(insert-file-contents "/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil)
  apply(tramp-sh-file-name-handler insert-file-contents ("/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil))
  tramp-file-name-handler(insert-file-contents "/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil)
  insert-file-contents("/loopback:krug:/tmp/tramp.VKkVY4" nil nil nil nil)
  insert-file-contents-literally("/loopback:krug:/tmp/tramp.VKkVY4")
  tramp-sh-handle-make-process(:name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buffer *EGLOT (
  apply(tramp-sh-handle-make-process (:name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls")
:connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buffer *
  tramp-sh-file-name-handler(make-process :name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buff
  apply(tramp-sh-file-name-handler make-process (:name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr
  tramp-file-name-handler(make-process :name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buffer
  make-process(:name "EGLOT (project/python-mode)" :command ("sh" "-c" "stty raw > /dev/null; pyls") :connection-type pipe :coding utf-8-emacs-unix :noquery t :stderr #<buffer *EGLOT (project/python-m
  #f(compiled-function () #<bytecode 0x4cc6b877eb18e4f>)()
  #f(compiled-function (cl--cnm conn slots) #<bytecode 0x1e62ad5e5cb986fa>)(#f(compiled-function (&rest cnm-args) #<bytecode 0x69d8e578fbe01b9>) #<eglot-lsp-server eglot-lsp-server-155d58fb815c> (:nam
  apply(#f(compiled-function (cl--cnm conn slots) #<bytecode 0x1e62ad5e5cb986fa>) #f(compiled-function (&rest cnm-args) #<bytecode 0x69d8e578fbe01b9>) (#<eglot-lsp-server eglot-lsp-server-155d58fb815c
  #f(compiled-function (&rest args) #<bytecode -0x614c7f3b221184a>)(#<eglot-lsp-server eglot-lsp-server-155d58fb815c> (:name "EGLOT (project/python-mode)" :events-buffer-scrollback-size 2000000 :notif
  apply(#f(compiled-function (&rest args) #<bytecode -0x614c7f3b221184a>) #<eglot-lsp-server eglot-lsp-server-155d58fb815c>
(:name "EGLOT (project/python-mode)" :events-buffer-scrollback-size 2000000
  initialize-instance(#<eglot-lsp-server eglot-lsp-server-155d58fb815c> (:name "EGLOT (project/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (serve
  #f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is called w
  apply(#f(compiled-function (class &rest slots) "Default constructor for CLASS `eieio-default-superclass'.\nSLOTS are the initialization slots used by `initialize-instance'.\nThis static method is ca
  make-instance(eglot-lsp-server :name "EGLOT (project/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode -0x12e904da4
  apply(make-instance eglot-lsp-server :name "EGLOT (project/python-mode)" :events-buffer-scrollback-size 2000000 :notification-dispatcher #f(compiled-function (server method params) #<bytecode -0x12e
  eglot--connect(python-mode (transient . "/loopback:krug:/tmp/eglot--fixtureQsFHHj/project/") eglot-lsp-server ("pyls"))
  apply(eglot--connect (python-mode (transient . "/loopback:krug:/tmp/eglot--fixtureQsFHHj/project/") eglot-lsp-server ("pyls")))
  eglot--tests-connect()
  #f(compiled-function () #<bytecode -0xb371af455e99614>)()
  eglot--call-with-fixture((("project" ("coiso.py" . "bla") ("merdix.py" . "bla")) ("anotherproject" ("cena.py" . "bla"))) #f(compiled-function () #<bytecode -0xb371af455e99614>))
  eglot-tests---auto-detect-running-server-1()
  #f(compiled-function () #<bytecode 0x19adf36146819a9f>)()
  ert--run-test-internal(#s(ert--test-execution-info :test ... :result ... :exit-continuation #f(compiled-function () #<bytecode 0xa3786383dad583>) :next-debugger debug :ert-debug-on-error nil))
  ert-run-test(#s(ert-test :name eglot--tramp-test :documentation "Ensure LSP servers can be used o..." :body #f(compiled-function () #<bytecode 0x19adf36146819a9f>) :most-recent-result #s(ert-test-fa
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests ... :test-map #<hash-table eql 43/43 0x155d58f115bd> :test-results
... :test-start-times ... :test-end-times ... :passed-expected 7 :passed-une
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #<bytecode -0x78e624d0b6f97a5>) nil)
  ert-run-tests-batch(t)
  ert-run-tests-batch-and-exit(t)
  eval((ert-run-tests-batch-and-exit 't) t)
  command-line-1(("-f" "package-initialize" "-L" "." "-l" "eglot" "-l" "eglot-tests" "--eval" "(setq ert-batch-backtrace-right-margin 200)" "--eval" "(ert-run-tests-batch-and-exit (quote t))"))
  command-line()
  normal-top-level()
Test eglot--tramp-test condition:
    (wrong-type-argument "inserted-chars 23")
   FAILED  10/43  eglot--tramp-test (0.578749 sec)
   passed  11/43  eglot-capabilities (0.000092 sec)
```

2021-03-04 16:21 UTC, bjc commented
I have `pyls` installed, which is why it's found in the PATH, but `python-mode` in `eglot-server-programs` is set to "jedi-language-server", so it gets used in the tests I've been running. When I change it to "pyls" I have completely separate issues where it doesn't even look like it's starting properly (I assume there's something wrong with my install of it).

Your backtrace doesn't make any sense to me. It looks like something's going wrong in TRAMP itself? I'll see what I can dig up.

2021-03-04 16:22 UTC, joaotavora commented
@bjc but when you `make check` your configuration should be completely bypassed, and that's pretty improtant.

2021-03-04 16:25 UTC, bjc commented
Oh, is the previous backtrace from Emacs 26? I don't have that installed, but maybe there's a dependency on a newer TRAMP that I'm not aware of. But if so, since we're only concerned with support for 27+, I don't know how important that actually is.

The second backtrace just shows that `pyls` isn't being found in the PATH for some reason.

The configuration isn't being bypassed -- since I never got `pyls` to work, I modified `eglot.el` with the language server change, under the assumption that I have some issue with my install of `pyls` and wanting to get some work done. I just never pushed the change up.

2021-03-04 16:27 UTC, bjc commented
I'm going to see if I can figure out what's wrong with `pyls` and work from there, since it seems that's the difference between working and not-working tests.

2021-03-04 16:38 UTC, bjc commented
> No sorry, from Emacs 28. Sorry for not being specific.

Ok, that's my main Emacs, so it's not a problem for me to test there.

> > The second backtrace just shows that pyls isn't being found in the PATH for some reason.
> 
> Yes, but it should be I have it in my path . So maybe there's something wrong with that specific test. It mustn't fail like that.

Agreed, but at least its tractable.

> Wait, so all these tests you've been running are against a modified `eglot.el`, or did I miss something? You have to run them against the `eglot.el` that we're proposing in this PR, not anything else!

I've only changed the one language server. Everything else is unmodified. And that language server change was only because `pyls` has proven to be problematic on my system. Whereas, `jedi-language-server` works just fine, as do `rls` and `rust-analyzer`, both of which I'm currently using with eglot over TRAMP.

`pyls`, for some reason, is just not something I can test right now. Here's what it looks like when I try to run it from the command line:
```shell
emacs27:~/emacs-lisp/eglot% pyls                                            ±[●][bjc/tramp-support]
Traceback (most recent call last):
  File "/home/bjc/.local/bin/pyls", line 5, in <module>
    from pyls.main import main
  File "/home/bjc/.local/lib/python3.9/site-packages/pyls/main.py", line 65
    print '%s%s' % ('    ' * indent, name)
          ^
SyntaxError: invalid syntax
```

As you can see, the issue isn't with eglot, but pyls itself. I'm going to see if I can fix it, because I would hate for this patch to be held up on account of not being able to test with it, but hopefully you can see why I've opted to change the python language server I'm using for testing.

2021-03-04 16:42 UTC, bjc commented
Turns out I should have done some digging sooner. I'm not the only one with this problem: https://github.com/palantir/python-language-server/issues/631

Installing the *correct* `python-language-server` has fixed that issue. I'll see about fixing the tests now.

As far as `jedi-language-server` vs `pyls` I have no opinion. I only used the former because my (incorrect) install of the latter seemed to be broken.

2021-03-04 18:53 UTC, bjc commented
I've tracked down the issue, but I'm unsure how to resolve it. It is, indeed, a `PATH` problem. By default, TRAMP ignores a users custom `PATH`, such as what may be set in your `.profile`, and only uses the system value.

You can change this behavior with the following elisp:
```emacs-lisp
(add-to-list 'tramp-remote-path 'tramp-own-remote-path)
```

I'd added that to my `.emacs` some time ago and had forgotten about it, which is why I didn't have the issue until I used the `make` test method.

The easiest thing to do would be amend the test by binding `tramp-remote-path` in a `let` form and `cons`ing `tramp-own-remote-path` to it:

```emacs-lisp
(ert-deftest eglot--tramp-test ()
  "Ensure LSP servers can be used over TRAMP."
  (skip-unless (or (>= emacs-major-version 27) (executable-find "pyls")))
  ;; Set up a loopback TRAMP method that’s just a shell so the remote
  ;; host is really just the local host.
  (let ((tramp-remote-path (cons 'tramp-own-remote-path tramp-remote-path))
	(tramp-methods '(("loopback"
…
```

I'm somewhat ambivalent about this solution. It works, but feels a bit hacky. I can't see a better solution right now, though.

2021-03-04 19:01 UTC, joaotavora commented
> The easiest thing to do would be amend the test by binding tramp-remote-path in a let form and consing tramp-own-remote-path to it:

What's your concern about it?  I think it should work...

2021-03-04 19:06 UTC, bjc commented
Thinking about it more, since the `make` method is how the test is supposed to be run, and it has a clean environment, I think it's fine.

Even in the case of running from within Emacs, where it may be set already, it doesn't really cause any harm. So I've pushed the change up.

2021-03-04 19:22 UTC, joaotavora commented
Great, all tests pass here, I'm sqaushing this up for the master branch.  Only one final hurdle remains:  do you have a FSF copyright assignment?  your name is not "Brendan" right?

2021-03-04 19:26 UTC, joaotavora commented
Your change can go in early regadless, but if you somehow oppose getting one for the FSF, I'll have to revert and reimplement your work.  Because the solution is so simple (a very good thing!), it _might_ count as a "trivial" contribution.  I'm hailing @monnier, former maintainer of Emacs, who should know about these things.

2021-03-04 19:37 UTC, joaotavora commented
> Brendan may be my brother. It's entirely possible he's signed an FSF agreement. 

His name might have popped up in the copyright file I have access to ;-)

Anyway, please write to `emacs-devel@gnu.org` and request a copyright assignment form, giving minimal context such as a link to this PR. They will mail the form offline to you.  I'm going to write in the commit message that you have requested it.

2021-03-04 22:36 UTC, monnier commented
>> Brendan may be my brother. It's entirely possible he's signed an FSF agreement. 
> His name might have popped up in the copyright file I have access to ;-)
> Anyway, please write to `emacs-devel@gnu.org` and request a copyright

No need for that.  Just fill the form below and send it as instructed to
the FSF so they can send you the relevant paperwork to sign.


        Stefan


Please email the following information to assign@gnu.org, and we
will send you the assignment form for your past and future changes.

Please use your full legal name (in ASCII characters) as the subject
line of the message.
----------------------------------------------------------------------
REQUEST: SEND FORM FOR PAST AND FUTURE CHANGES

[What is the name of the program or package you're contributing to?]
Emacs

[Did you copy any files or text written by someone else in these changes?
Even if that material is free software, we need to know about it.]


[Do you have an employer who might have a basis to claim to own
your changes?  Do you attend a school which might make such a claim?]


[For the copyright registration, what country are you a citizen of?]


[What year were you born?]


[Please write your email address here.]


[Please write your postal address here.]





[Which files have you changed so far, and which new files have you written
so far?]

2021-03-06 01:36 UTC, bjc commented
I submitted the form yesterday, and am awaiting response. I'll let you know when everything's done.

2021-03-06 16:27 UTC, closed without merging

2021-03-06 16:28 UTC, joaotavora commented
In the meantime, I pushed this to master.  Let's be aware of possible bug reports in the next weeks.

2021-03-11 23:45 UTC, bjc commented
I just got word that the copyright assignment is finished, so there should be no further issues.

2021-03-11 23:52 UTC, joaotavora commented
> I just got word that the copyright assignment is finished,

kööl

> so there should be no further issues.

_famous last words_  :sweat_smile:  I wonder if anyone's actually using this.  Anyway, it's a very minimal implementation, it should be relatively easy to debug.